version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Starting build phase..."
      - echo "Building Docker image..."
      #- docker build -t wild_rydes_app.py .
  post_build:
    commands:
      - echo "Starting post_build phase..."
