name: Snyk Security Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        
      - name: Authenticate Snyk
        run: npx snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Run Snyk security check
        run: npx snyk test --all-projects
